# Generated by Django 3.2.9 on 2021-12-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_tips_catgory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='user',
        ),
    ]
