# Generated by Django 3.2.7 on 2021-12-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='date',
        ),
    ]
