# Generated by Django 3.2.9 on 2021-12-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211222_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='age',
            field=models.CharField(choices=[('0-3', '0-3'), ('3-6', '3-6'), ('6-9', '6-9'), ('9-12', '9-12'), ('12-24', '12-24')], default='0-3', max_length=5),
        ),
    ]
