# Generated by Django 3.2.7 on 2021-12-01 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_tips_catgory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='Name',
        ),
        migrations.AddField(
            model_name='tips',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
