# Generated by Django 3.2.7 on 2021-12-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211201_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='user',
        ),
        migrations.AddField(
            model_name='tips',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
